Nedgraderer fp-felles pga jackson (#816)
### Behov / Bakgrunn
no.nav.vedtak.exception.TekniskException: FP-713328: Fikk
JacksonException ved deserialisering av JSON
Caused by: tools.jackson.databind.exc.InvalidDefinitionException:
Conflicting property-based creators: already had explicit creator
[method
no.nav.k9.kodeverk.behandling.FagsakYtelseType#fraObjektProp(java.lang.String)],
encountered another: [method
no.nav.k9.kodeverk.behandling.FagsakYtelseType#fraKode(java.lang.String)]

### Løsning
Nedgraderer til fp-felles v7.8 fordi 7.9 bruker Jackson 3 som er
strengere og fører til feilen over.
https://github.com/navikt/fp-felles/releases/tag/7.9.0
https://github.com/navikt/fp-graphql/releases/tag/1.1.0

---

### Sjekkliste for godkjenner

- [ ] Ingen uhensiktsmessig spesialbehandling av saker (hardkodede
aktørId-er, saksnumre, org.nr som styrer forretningslogikk)
- [ ] Flyway-migrasjoner er vurdert (destruktive endringer, korrekt
versjonering, påvirkning på økonomiske data)
- [ ] Sporbarhet: lenke til Jira, Slack-tråd, eller en tydelig
beskrivelse av **hvorfor** endringen gjøres